export const actionType = {
  FETCH_LOGIN_REQUEST: "FETCH_LOGIN_REQUEST",
  FETCH_LOGIN_SUCCESS: "FETCH_LOGIN_SUCCESS",
  FETCH_LOGIN_FAILURE: "FETCH_LOGIN_FAILURE",
  RESET_STORE: "RESET_STORE",

  FETCH_PROFILE_REQUEST: "FETCH_PROFILE_REQUEST",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",

  FETCH_JOBS_REQUEST: "FETCH_JOBS_REQUEST",
  FETCH_JOBS_SUCCESS: "FETCH_JOBS_SUCCESS",
  FETCH_JOBS_FAILURE: "FETCH_JOBS_FAILURE",

  APPLY_FOR_JOB_SUCCESS: "APPLY_FOR_JOB_SUCCESS",

  CREATE_JOB_REQUEST: "CREATE_JOB_REQUEST",
  CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAILURE: "CREATE_JOB_FAILURE",

  GET_JOB_REQUEST: "GET_JOB_REQUEST",
  GET_JOB_SUCCESS: "GET_JOB_SUCCESS",
  GET_JOB_FAILURE: "GET_JOB_FAILURE",

  GET_ALL_RESUMES_REQUEST: "GET_ALL_RESUMES_REQUEST",
  GET_ALL_RESUMES_SUCCESS: "GET_ALL_RESUMES_SUCCESS",
  GET_ALL_RESUMES_FAILURE: "GET_ALL_RESUMES_FAILURE",
  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
};
